version: '3'
services:
  web:
    build:
      context: .
      args:
        - BUILD_REACT_APP_INSIGHTS_KEY=$REACT_APP_INSIGHTS_KEY
    image: eliakaris/blog
    volumes:
    - ./.output:/usr/src/app/.output
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
