version: "3"
services:
  integration-tests:
    build:
      context: ./integration-tests
    image: eliakaris/tests
    volumes:
      - ./.output:/usr/src/app/.output
    depends_on:
      - web
      - selenium
  web:
    build:
      context: .
      args:
        - BUILD_REACT_APP_INSIGHTS_KEY=$REACT_APP_INSIGHTS_KEY
    ports:
      - "3000:3000"
    image: eliakaris/web
    volumes:
      - ./.output:/usr/src/app/.output
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
