version: '3'
services:
  integration-tests:
    build:
      context: ./integration-tests
    image: eliakaris/tests
    volumes:
      - ./.output:/usr/src/app/.output
    ports:
      - "3002:3002"
    depends_on:
      - prod
      - selenium
  web:
    build:
      context: ./web
      args:
        - BUILD_REACT_APP_INSIGHTS_KEY=$REACT_APP_INSIGHTS_KEY
    ports:
      - "3000:3000"
    image: eliakaris/blog
    volumes:
      - ./.output:/usr/src/app/.output
    depends_on:
      - server
  server:
    build:
      context: ./server
    image: eliakaris/server
    ports:
      - "3001:3001"
  prod:
    build:
      context: ./reverse-proxy
    ports:
      - "8080:8080"
    image: eliakaris/prod-proxy
    restart: always
    depends_on:
      - web
      - server
  selenium:
    image: selenium/standalone-chrome
