version: '3'
services:
  web:
    build: .
    image: eliakaris/blog
    environment:
    - REACT_APP_INSIGHTS_KEY
    volumes:
    - ./.output:/usr/src/app/.output
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
