// src/constants/index.tsx

export const REQUEST_BLOG_ENTRIES = 'REQUEST_BLOG_ENTRIES';
export type REQUEST_BLOG_ENTRIES = typeof REQUEST_BLOG_ENTRIES;

export const REQUEST_BLOG_ENTRIES_SUCCESS = 'REQUEST_BLOG_ENTRIES_SUCCESS';
export type REQUEST_BLOG_ENTRIES_SUCCESS = typeof REQUEST_BLOG_ENTRIES_SUCCESS;

export const REQUEST_BLOG_ENTRIES_FAIL = 'REQUEST_BLOG_ENTRIES_FAIL';
export type REQUEST_BLOG_ENTRIES_FAIL = typeof REQUEST_BLOG_ENTRIES_FAIL;

export const REQUEST_BLOG_ENTRY = 'REQUEST_BLOG_ENTRY';
export type REQUEST_BLOG_ENTRY = typeof REQUEST_BLOG_ENTRY;

export const REQUEST_BLOG_ENTRY_SUCCESS = 'REQUEST_BLOG_ENTRY_SUCCESS';
export type REQUEST_BLOG_ENTRY_SUCCESS = typeof REQUEST_BLOG_ENTRY_SUCCESS;

export const REQUEST_BLOG_ENTRY_FAIL = 'REQUEST_BLOG_ENTRY_FAIL';
export type REQUEST_BLOG_ENTRY_FAIL = typeof REQUEST_BLOG_ENTRY_FAIL;